from __future__ import annotations

from sanara.drc.transforms.core import (
    t1_public_access_block,
    t2_s3_sse,
    t3_s3_versioning,
    t4_rds_not_public,
    t5_ebs_encrypted,
    t6_ebs_default,
    t7_sns_encrypted,
    t8_sqs_encrypted,
    t9_dynamodb_pitr,
    t10_log_group_encrypted,
    t11_s3_acl_private,
    t12_dynamodb_kms_cmk,
    t13_kms_key_rotation,
    t14_s3_policy_secure_transport,
    t15_s3_sse_kms,
    t16_s3_access_logging,
    t17_kms_key_policy_present,
    t18_s3_acl_disabled,
    t19_s3_event_notifications_enabled,
    t20_lambda_tracing,
    t21_rds_deletion_protection,
    t22_ecr_scan_on_push,
    t23_cloudtrail_log_file_validation,
    t24_cloudtrail_kms,
    t25_ecr_kms_encryption,
    t26_ec2_imdsv2,
    t27_rds_backup_retention,
    t28_secretsmanager_kms,
    t29_cloudtrail_multi_region,
    t30_rds_storage_encrypted,
)

REGISTRY = {
    "aws.s3.public_access_block": t1_public_access_block,
    "aws.s3.sse_default": t2_s3_sse,
    "aws.s3.versioning_enabled": t3_s3_versioning,
    "aws.rds.not_public": t4_rds_not_public,
    "aws.ebs.encrypted": t5_ebs_encrypted,
    "aws.ebs.default_encryption_enabled": t6_ebs_default,
    "aws.sns.encrypted": t7_sns_encrypted,
    "aws.sqs.encrypted": t8_sqs_encrypted,
    "aws.dynamodb.pitr_enabled": t9_dynamodb_pitr,
    "aws.cloudwatch.log_group_encrypted": t10_log_group_encrypted,
    "aws.s3.acl_private": t11_s3_acl_private,
    "aws.dynamodb.kms_cmk_encrypted": t12_dynamodb_kms_cmk,
    "aws.kms.rotation_enabled": t13_kms_key_rotation,
    "aws.s3.policy_secure_transport": t14_s3_policy_secure_transport,
    "aws.s3.sse_kms_default": t15_s3_sse_kms,
    "aws.s3.access_logging_enabled": t16_s3_access_logging,
    "aws.kms.policy_present": t17_kms_key_policy_present,
    "aws.s3.acl_disabled": t18_s3_acl_disabled,
    "aws.s3.event_notifications_enabled": t19_s3_event_notifications_enabled,
    "aws.lambda.tracing_enabled": t20_lambda_tracing,
    "aws.rds.deletion_protection": t21_rds_deletion_protection,
    "aws.ecr.scan_on_push": t22_ecr_scan_on_push,
    "aws.cloudtrail.log_file_validation": t23_cloudtrail_log_file_validation,
    "aws.cloudtrail.kms_encrypted": t24_cloudtrail_kms,
    "aws.ecr.kms_encryption": t25_ecr_kms_encryption,
    "aws.ec2.imdsv2_required": t26_ec2_imdsv2,
    "aws.rds.backup_retention": t27_rds_backup_retention,
    "aws.secretsmanager.kms_encrypted": t28_secretsmanager_kms,
    "aws.cloudtrail.multi_region_enabled": t29_cloudtrail_multi_region,
    "aws.rds.storage_encrypted": t30_rds_storage_encrypted,
}
